id: P000351
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29982
  title: མན་ངག་རྒྱུད་དང་ཕྱི་མ་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཀྱི་ཚུལ་དུ་བཀོད་པ་ཕན་བདེའི་ནོར་བུའི་བང་མཛོད
  author: ''
  volumes:
    5dde661fa2ca498694ff3635fd52becd:
      image_group_id: I1PD384
      title: Volume 1 of man ngag rgyud dang phyi ma rgyud kyi lhan thabs kyi tshul
        du bkod pa phan bde'i nor bu'i bang mdzod
      volume_number: 1
      total_pages: 974
      base_file: v001.txt
